### ISSUE TITLE
Allow failure on download of JSON files

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/scikit-validate#10]
Currently, the report stage is failing if a download of a JSON fails.
In some cases, e.g. software_versions, this is OK as that JSON is not critical.

&rarr; add `allow_failure` keyword for download_json, e.g.
```
download_json:
  software_versions: software_versions.json
```
&rarr;
```
download_json:
  software_versions:
   path: software_versions.json
   allow_failure: true
```
